#!/bin/sh

MODEL=""
PORT=8080
MODELDIR=~/.r2ai.models
LLAMA=llamafile
[ -z "${R2AI}" ] && R2AI=r2ai

main() {
	if [ -z "${MODEL}" ]; then
		echo "Use -l and -m to select a model" >&2
		exit 1
	fi
	echo "${MODEL}" | grep -e ^/
	if [ $? = 0 ]; then
		MODELPATH="${MODEL}"
	else
		MODELPATH="${MODELDIR}/${MODEL}.gguf"
	fi
	case ${LLAMA} in
	llamafile)
		llamafile --server --nobrowser -c 0 --port ${PORT} -m "${MODELPATH}"
		;;
	llamacpp)
		llama-server -c 0 --port ${PORT} -m "${MODELPATH}"
		;;
	koboldcpp)
		koboldcpp -c 0 --port ${PORT} -m "${MODELPATH}"
		;;
	r2ai)
		${R2AI} -c="-e http.port=${PORT}" -m "${MODEL}" -w
		;;
	*)
		echo "Invalid llama server selected."
		;;
	esac
}

help() {
	cat <<EOF
Usage: r2ai-server [-flags]
-m         list models
-m [name]  select given model
-l         list llama servers available
-l [name]  select llama software
-h         show this help message
-p [port]  select port
EOF
}

models() {
	cd "${MODELDIR}" || exit 1
	ls | sed -e 's,.gguf$,,'
	exit 0
}

llamas() {
	echo r2ai
	echo llamafile
	echo llamacpp
	echo koboldcpp
}

while : ; do
	case "$1" in
	-l)
		if [ -z "$2" ]; then
		llamas
		break
		fi
		LLAMA="$2"
		shift
		;;
	-m)
		if [ -z "$2" ]; then
		models
		break
		fi
		MODEL="$2"
		shift
		;;
	-p)
		PORT="$2"
		shift
		;;
	-h)
		help
		;;
	"")
		main
		break
		;;
	esac
	shift
done
