name: Build and publish r2ai

env:
  R2V: 6.0.4
  ZIP_PREFIX: r2ai-

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }} / ${{ matrix.build_system }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]
        build_system: [make, meson]
        # Windows builds should be meson-only
        exclude:
          - os: windows-latest
            build_system: make

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup common tools (meson/ninja when needed)
        if: matrix.build_system == 'meson' && matrix.os != 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja

      - name: Install radare2 on Linux
        if: matrix.os == 'ubuntu-24.04'
        run: |
          wget "https://github.com/radareorg/radare2/releases/download/${R2V}/radare2_${R2V}_amd64.deb"
          wget "https://github.com/radareorg/radare2/releases/download/${R2V}/radare2-dev_${R2V}_amd64.deb"
          sudo dpkg -i "radare2_${R2V}_amd64.deb"
          sudo dpkg -i "radare2-dev_${R2V}_amd64.deb"

      - name: Install radare2 on macOS
        if: matrix.os == 'macos-latest'
        run: |
          git clone --depth=1 --branch "${{env.R2V}}" https://github.com/radareorg/radare2
          cd radare2
          sys/install.sh

      - name: Build with Make
        if: matrix.build_system == 'make'
        run: make -C src

      - name: Build with Meson (Unix)
        if: matrix.build_system == 'meson' && matrix.os != 'windows-latest'
        run: |
          cd src
          meson setup build -Dr2_prefix=${{ secrets.R2_PREFIX }} || meson configure build
          meson compile -C build

      - name: Setup Meson/Ninja on Windows
        if: matrix.build_system == 'meson' && matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja
        shell: powershell

      - name: Build with Meson (Windows, MSVC)
        if: matrix.build_system == 'meson' && matrix.os == 'windows-latest'
        run: |
          cd src
          meson setup build -Dr2_prefix=${{ secrets.R2_PREFIX }}
          if ($LASTEXITCODE -ne 0) { meson configure build }
          meson compile -C build
        shell: powershell

      - name: Prepare artifact (only for tag pushes)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p release
          # Copy likely outputs into release/ for zipping
          cp src/r2ai* release/ || true
          # Also copy meson build outputs if present
          cp -r src/build/* release/ 2>/dev/null || true
          zip -j release/${ZIP_PREFIX}${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.build_system }}.zip release/* || true

      - name: Upload artifact (tag only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.build_system }}-binary
          path: release/${ZIP_PREFIX}${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.build_system }}.zip

  release:
    name: Publish release (tags only, only if tag points to main)
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure tag commit is on main
        run: |
          git fetch origin main:refs/remotes/origin/main
          # If the tagged commit is not contained in origin/main, skip publishing
          if git branch -r --contains ${GITHUB_SHA} | grep -q "origin/main"; then
            echo "Tag commit is on origin/main, continuing release."
          else
            echo "Tag commit is not on origin/main — skipping release.";
            exit 0
          fi

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List downloaded artifacts
        run: find release-artifacts -type f -maxdepth 4 -print

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-artifacts/**/*.zip
          generate_release_notes: true
